helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-lite-wiki
    forcestring: true
  - name: image.tag
    value: main@sha256:cd86837eb686ac6d73105e54fedd12708cf1b39c6a029deec5088070c21f464c
    forcestring: true
