helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-lite-wiki
    forcestring: true
  - name: image.tag
    value: main@sha256:fa3f77c9209c0f136ad7a315bec8b6c5f2e5c2575027a8e543c81902f797ec3f
    forcestring: true
